services:
  backend:
    build:
      context: ./backend


  proxy:
    image: nginx
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 8080:8080
    depends_on: 
      - backend

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'